version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/UserR00T/Website

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-8-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-8-dependencies-

      - run: yarn install --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: node-8-dependencies-{{ checksum "package.json" }}

      # run build
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "SHA256:LhsEOPxQE8eadV8HuJBPnMfe++DXFe61cl6f7A/6pik"
      - deploy:
          name: Deploy to VPS
          command: scp -o "StrictHostKeyChecking no" -r dist/* www-deployment@UserR00T.com:/var/www/userr00t.com/html/
