version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/UserR00T/Website

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-8-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-8-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-8-dependencies-{{ checksum "package.json" }}

      # run build
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "31:65:c5:08:f8:79:41:32:9c:98:6f:bc:e9:8a:46:20"
      - run: scp -r UserR00T/Website/dist/* root@UserR00T.com:/var/www/userr00t.com/html/
